openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /pets:
    $ref: ./paths/pets/index.yaml
  /pets/{petId}:
    $ref: ./paths/pets/id/index.yaml
components:
  schemas:
    $refs:
      - ./components/schemas/pet.yaml
      - ./components/schemas/pets.yaml
    Error:
      $ref: ./components/schemas/error.yaml
