name: 'PR Diff Tree'
description: 'This action provide a comment that displays the diff of the pull request in a tree format.'
author: 'wadackel'
inputs:
  token:
    required: true
    description: 'GITHUB_TOKEN as provided by secrets'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: white
  icon: git-pull-request
