name: Node.js Package and Docker publish
on:
  release:
    types: [created]
jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set release version
        id: release_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v}
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  docker:
    runs-on: ubuntu-latest
    needs: npm
    steps:
      - uses: actions/checkout@v2
      - name: Push to Docker Hub
        run: |
          VERSION=${GITHUB_REF/refs\/tags\/v}
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker build -t keisuke6065/openapi-combine:$VERSION . --build-arg version=$VERSION
          docker push keisuke6065/openapi-combine:$VERSION
