name: Publish

on:
  release:
    types: [published]

jobs:
  push:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          repository: ruby/ruby-ci-image/ci
          tag_with_ref: true
