name: Publish

on:
  release:
    types: [published]

jobs:
  push:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.ACCESS_TOKEN }}
          registry: ghcr.io
          repository: ruby/ruby-ci-image
          tag_with_ref: true
